=== xdgrulez/xdk/Compiler/XML/xdk.dtd
<!ENTITY % type "(typeDomain|typeSet|typeISet|typeTuple|typeList|typeRecord|typeValency|typeCard|typeVec|typeInt|typeInts|typeString|typeBool|typeRef|typeLabelRef|typeVariable)">
<!ENTITY % types "(%type;*)">
<!ENTITY % term "(constant|variable|integer|top|bot|constantCard|constantCardSet|constantCardInterval|variableCard|variableCardSet|variableCardInterval|set|list|record|setGen|featurePath|annotation|conj|disj|concat|order|bounds|feature|varFeature)">
<!ENTITY % terms "(%term;*)">
<!ENTITY % class "(classDimension|useClass|classConj|classDisj)">
<!ENTITY % classes "(%class;*)">
<!ENTITY % recSpec "(feature|varFeature|recordConj|recordDisj)">
<!ENTITY % recSpecs "(%recSpec;*)">
<!ENTITY % setGenSpec "(constant|setGenConj|setGenDisj)">
<!ENTITY % setGenSpecs "(%setGenSpec;*)">

<!ENTITY principleDefs SYSTEM "../../Solver/Principles/principles.xml">
<!ENTITY outputDefs SYSTEM "../../Outputs/outputs.xml">

<!ELEMENT grammar (principleDef*,outputDef*,useDimension*,dimension*,classDef*,entry*)>
<!ELEMENT principleDef EMPTY>
<!ATTLIST principleDef id ID #REQUIRED>
<!ELEMENT outputDef EMPTY>
<!ATTLIST outputDef id ID #REQUIRED>
<!ELEMENT useDimension EMPTY>
<!ATTLIST useDimension idref IDREF #REQUIRED>
<!ELEMENT dimension (attrsType?,entryType?,labelType?,typeDef*,usePrinciple*,output*,useOutput*)>
<!ATTLIST dimension id ID #REQUIRED>
<!ELEMENT attrsType %type;>
<!ELEMENT entryType %type;>
<!ELEMENT labelType %type;>
<!ELEMENT output EMPTY>
<!ATTLIST output idref IDREF #REQUIRED>
<!ELEMENT useOutput EMPTY>
<!ATTLIST useOutput idref IDREF #REQUIRED>

<!ELEMENT typeDef %type;>
<!ATTLIST typeDef id ID #REQUIRED>

<!ELEMENT typeDomain (constant*)>
<!ELEMENT typeSet %type;>
<!ELEMENT typeISet %type;>
<!ELEMENT typeTuple %types;>
<!ELEMENT typeList %type;>
<!ELEMENT typeRecord (typeFeature*)>
<!ELEMENT typeValency %type;>
<!ELEMENT typeCard EMPTY>
<!ELEMENT typeVec (%type;,%type;)>
<!ELEMENT typeInt EMPTY>
<!ELEMENT typeInts EMPTY>
<!ELEMENT typeString EMPTY>
<!ELEMENT typeBool EMPTY>
<!ELEMENT typeRef EMPTY>
<!ATTLIST typeRef idref IDREF #REQUIRED>
<!ELEMENT typeLabelRef EMPTY>
<!ATTLIST typeLabelRef data CDATA #REQUIRED>
<!ELEMENT typeVariable EMPTY>
<!ELEMENT typeUnion %types;>

<!ELEMENT typeFeature %type;>
<!ATTLIST typeFeature
          data CDATA #REQUIRED>
<!ELEMENT feature %term;>
<!ATTLIST feature
          data CDATA #REQUIRED>
<!ELEMENT varFeature %term;>
<!ATTLIST varFeature
          data CDATA #REQUIRED>

<!ELEMENT usePrinciple (dim*,arg*)>
<!ATTLIST usePrinciple idref IDREF #REQUIRED>
<!ELEMENT dim EMPTY>
<!ATTLIST dim
          var CDATA #REQUIRED
	  idref IDREF #REQUIRED>
<!ELEMENT arg %term;>
<!ATTLIST arg
          var CDATA #REQUIRED>
     
<!ELEMENT classDef (variable*,%classes;)>
<!ATTLIST classDef 
          id ID #REQUIRED>

<!ELEMENT classDimension %term;>
<!ATTLIST classDimension idref IDREF #REQUIRED>
<!ELEMENT useClass (varFeature*)>
<!ATTLIST useClass idref IDREF #REQUIRED>
<!ELEMENT classConj %classes;>
<!ELEMENT classDisj %classes;>

<!ELEMENT entry %classes;>

<!ELEMENT constant EMPTY>
<!ATTLIST constant data CDATA #REQUIRED>
<!ELEMENT integer EMPTY>
<!ATTLIST integer data CDATA #REQUIRED>
<!ELEMENT top EMPTY>
<!ELEMENT bot EMPTY>
<!ELEMENT variable EMPTY>
<!ATTLIST variable data CDATA #REQUIRED>
<!ELEMENT constantCard EMPTY>
<!ATTLIST constantCard
          data CDATA #REQUIRED
	  card (one|opt|any|geone) "one">
<!ELEMENT constantCardSet (integer*)>
<!ATTLIST constantCardSet
          data CDATA #REQUIRED>
<!ELEMENT constantCardInterval (integer,integer)>
<!ATTLIST constantCardInterval
          data CDATA #REQUIRED>
<!ELEMENT variableCard EMPTY>
<!ATTLIST variableCard
          data CDATA #REQUIRED
	  card (one|opt|any|geone) "one">
<!ELEMENT variableCardSet (integer*)>
<!ATTLIST variableCardSet
          data CDATA #REQUIRED>
<!ELEMENT variableCardInterval (integer,integer)>
<!ATTLIST variableCardInterval
          data CDATA #REQUIRED>
<!ELEMENT set %terms;>
<!ELEMENT list %terms;>
<!ELEMENT record %recSpecs;>
<!ELEMENT recordConj %recSpecs;>
<!ELEMENT recordDisj %recSpecs;>
<!ELEMENT setGen %setGenSpecs;>
<!ELEMENT setGenConj %setGenSpecs;>
<!ELEMENT setGenDisj %setGenSpecs;>
<!ELEMENT featurePath (constant*)>
<!ATTLIST featurePath
          root (down|up) #REQUIRED
          dimension CDATA #REQUIRED
          aspect (entry|attrs) #REQUIRED>
<!ELEMENT annotation (%term;,%type;)>
<!ELEMENT conj %terms;>
<!ELEMENT disj %terms;>
<!ELEMENT concat %terms;>
<!ELEMENT order %terms;>
<!ELEMENT bounds (%term;,%term;)>

=== xdgrulez/xdk/Grammars/Acl01PW.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE grammar SYSTEM "../Compiler/XML/xdk.dtd">
<grammar>
    <useDimension idref="id"/>
    <useDimension idref="lp"/>
    <useDimension idref="idlp"/>
    <useDimension idref="lex"/>
    <dimension id="id">
	<attrsType>
	    <typeRecord>
		<typeFeature data="agr">
		    <typeRef idref="id.agr"/>
		</typeFeature>
	    </typeRecord>
	</attrsType>
	<entryType>
	    <typeRecord>
		<typeFeature data="in">
		    <typeSet>
			<typeTuple>
			    <typeRef idref="id.label"/>
			    <typeDomain>
				<constant data="!"/>
				<constant data="?"/>
				<constant data="+"/>
				<constant data="*"/>
			    </typeDomain>
			</typeTuple>
		    </typeSet>
		</typeFeature>
		<typeFeature data="out">
		    <typeSet>
			<typeTuple>
			    <typeRef idref="id.label"/>
			    <typeDomain>
				<constant data="!"/>
				<constant data="?"/>
				<constant data="+"/>
				<constant data="*"/>
			    </typeDomain>
			</typeTuple>
		    </typeSet>
		</typeFeature>
		<typeFeature data="agrs">
		    <typeRef idref="id.agrs"/>
		</typeFeature>
		<typeFeature data="agree">
		    <typeSet>
			<typeRef idref="id.label"/>
		    </typeSet>
		</typeFeature>
	    </typeRecord>
	</entryType>
	<labelType>
	    <typeRef idref="id.label"/>
	</labelType>
	<typeDef id="id.label">
	    <typeDomain>
		<constant data="det"/>
		<constant data="subj"/>
		<constant data="obj"/>
		<constant data="vbse"/>
		<constant data="vprt"/>
		<constant data="vinf"/>
		<constant data="prt"/>
	    </typeDomain>
	</typeDef>
	<typeDef id="id.person">
	    <typeDomain>
		<constant data="first"/>
		<constant data="second"/>
		<constant data="third"/>
	    </typeDomain>
	</typeDef>
	<typeDef id="id.number">
	    <typeDomain>
		<constant data="sg"/>
		<constant data="pl"/>
	    </typeDomain>
	</typeDef>
	<typeDef id="id.gender">
	    <typeDomain>
		<constant data="masc"/>
		<constant data="fem"/>
		<constant data="neut"/>
	    </typeDomain>
	</typeDef>
	<typeDef id="id.case">
	    <typeDomain>
		<constant data="nom"/>
		<constant data="gen"/>
		<constant data="dat"/>
		<constant data="acc"/>
	    </typeDomain>
	</typeDef>
	<typeDef id="id.def">
	    <typeDomain>
		<constant data="def"/>
		<constant data="indef"/>
		<constant data="undef"/>
	    </typeDomain>
	</typeDef>
	<typeDef id="id.agr">
	    <typeTuple>
		<typeRef idref="id.person"/>
		<typeRef idref="id.number"/>
		<typeRef idref="id.gender"/>
		<typeRef idref="id.case"/>
		<typeRef idref="id.def"/>
	    </typeTuple>
	</typeDef>
	<typeDef id="id.agrs">
	    <typeISet>
		<typeRef idref="id.agr"/>
	    </typeISet>
	</typeDef>
	<usePrinciple idref="principle.graphPW">
	    <dim var="D" idref="id"/>

	</usePrinciple>
	<usePrinciple idref="principle.treePW">
	    <dim var="D" idref="id"/>

	</usePrinciple>
	<usePrinciple idref="principle.valencyPW">
	    <dim var="D" idref="id"/>

	</usePrinciple>
	<usePrinciple idref="principle.agrPW">
	    <dim var="D" idref="id"/>

	</usePrinciple>
	<usePrinciple idref="principle.agreementPW">
	    <dim var="D" idref="id"/>

	</usePrinciple>
	<usePrinciple idref="principle.governmentAcl01PW">
	    <dim var="D" idref="id"/>

	</usePrinciple>
	<output idref="output.dag"/>
	<output idref="output.latex"/>
	<output idref="output.decode"/>
	<output idref="output.pretty"/>
	<output idref="output.xml"/>
	<output idref="output.xml1"/>
	<output idref="output.xml2"/>
	<output idref="output.xml3"/>
	<output idref="output.xml4"/>

    </dimension>
    <dimension id="lp">
	<attrsType>
	    <typeRecord>

	    </typeRecord>
	</attrsType>
	<entryType>
	    <typeRecord>
		<typeFeature data="in">
		    <typeSet>
			<typeTuple>
			    <typeRef idref="lp.label"/>
			    <typeDomain>
				<constant data="!"/>
				<constant data="?"/>
				<constant data="+"/>
				<constant data="*"/>
			    </typeDomain>
			</typeTuple>
		    </typeSet>
		</typeFeature>
		<typeFeature data="out">
		    <typeSet>
			<typeTuple>
			    <typeRef idref="lp.label"/>
			    <typeDomain>
				<constant data="!"/>
				<constant data="?"/>
				<constant data="+"/>
				<constant data="*"/>
			    </typeDomain>
			</typeTuple>
		    </typeSet>
		</typeFeature>
		<typeFeature data="order">
		    <typeSet>
			<typeTuple>
			    <typeRef idref="lp.label"/>
			    <typeRef idref="lp.label"/>
			</typeTuple>
		    </typeSet>
		</typeFeature>
	    </typeRecord>
	</entryType>
	<labelType>
	    <typeRef idref="lp.label"/>
	</labelType>
	<typeDef id="lp.label">
	    <typeDomain>
		<constant data="df"/>
		<constant data="mf"/>
		<constant data="vcf"/>
		<constant data="pf"/>
		<constant data="vxf"/>
		<constant data="^"/>
	    </typeDomain>
	</typeDef>
	<usePrinciple idref="principle.graphPW">
	    <dim var="D" idref="lp"/>

	</usePrinciple>
	<usePrinciple idref="principle.treePW">
	    <dim var="D" idref="lp"/>

	</usePrinciple>
	<usePrinciple idref="principle.valencyPW">
	    <dim var="D" idref="lp"/>

	</usePrinciple>
	<usePrinciple idref="principle.orderPW">
	    <dim var="D" idref="lp"/>

	</usePrinciple>
	<usePrinciple idref="principle.projectivityPW">
	    <dim var="D" idref="lp"/>

	</usePrinciple>
	<output idref="output.dag"/>
	<output idref="output.latex"/>
	<output idref="output.decode"/>
	<output idref="output.pretty"/>

    </dimension>
    <dimension id="idlp">
	<attrsType>
	    <typeRecord>

	    </typeRecord>
	</attrsType>
	<entryType>
	    <typeRecord>
		<typeFeature data="blocks">
		    <typeSet>
			<typeRef idref="id.label"/>
		    </typeSet>
		</typeFeature>
		<typeFeature data="linkEnd">
		    <typeSet>
			<typeTuple>
			    <typeRef idref="lp.label"/>
			    <typeRef idref="id.label"/>
			</typeTuple>
		    </typeSet>
		</typeFeature>
	    </typeRecord>
	</entryType>
	<labelType>
	    <typeDomain>

	    </typeDomain>
	</labelType>

	<usePrinciple idref="principle.climbingPW">
	    <dim var="D1" idref="lp"/>
	    <dim var="D2" idref="id"/>

	</usePrinciple>
	<usePrinciple idref="principle.climbingSubgraphsPW">
	    <dim var="D1" idref="lp"/>
	    <dim var="D2" idref="id"/>

	</usePrinciple>
	<usePrinciple idref="principle.barriersPW">
	    <dim var="D1" idref="lp"/>
	    <dim var="D2" idref="id"/>
	    <dim var="D3" idref="idlp"/>

	</usePrinciple>
	<usePrinciple idref="principle.linkingEndPW">
	    <dim var="D1" idref="lp"/>
	    <dim var="D2" idref="id"/>
	    <dim var="D3" idref="idlp"/>

	</usePrinciple>


    </dimension>
    <dimension id="lex">
	<attrsType>
	    <typeRecord>

	    </typeRecord>
	</attrsType>
	<entryType>
	    <typeRecord>
		<typeFeature data="word">
		    <typeString/>
		</typeFeature>
	    </typeRecord>
	</entryType>
	<labelType>
	    <typeDomain>

	    </typeDomain>
	</labelType>

	<usePrinciple idref="principle.entries">


	</usePrinciple>
	<output idref="output.dags1"/>
	<output idref="output.latexs1"/>
	<output idref="output.pretty1"/>
	<useOutput idref="output.dags1"/>
    </dimension>
    <classDef id="det">
	<variable data="Word"/>
	<variable data="Agrs"/>
	<classConj>
	    <classDimension idref="id">
		<record>
		    <feature data="in">
			<set>
			    <constantCard data="det" card="opt"/>
			</set>
		    </feature>
		    <feature data="agrs">
			<variable data="Agrs"/>
		    </feature>
		</record>
	    </classDimension>
	    <classDimension idref="lp">
		<record>
		    <feature data="in">
			<set>
			    <constantCard data="df" card="opt"/>
			</set>
		    </feature>
		</record>
	    </classDimension>
	    <classDimension idref="lex">
		<record>
		    <feature data="word">
			<variable data="Word"/>
		    </feature>
		</record>
	    </classDimension>
	</classConj>
    </classDef>
    <classDef id="cnoun">
	<variable data="Word"/>
	<variable data="Agrs"/>
	<classConj>
	    <classDimension idref="id">
		<record>
		    <feature data="in">
			<set>
			    <constantCard data="subj" card="opt"/>
			    <constantCard data="obj" card="opt"/>
			</set>
		    </feature>
		    <feature data="out">
			<set>
			    <constantCard data="det" card="opt"/>
			</set>
		    </feature>
		    <feature data="agrs">
			<variable data="Agrs"/>
		    </feature>
		    <feature data="agree">
			<set>
			    <constant data="det"/>
			</set>
		    </feature>
		</record>
	    </classDimension>
	    <classDimension idref="lp">
		<record>
		    <feature data="in">
			<set>
			    <constantCard data="mf" card="opt"/>
			</set>
		    </feature>
		    <feature data="out">
			<set>
			    <constantCard data="df" card="opt"/>
			</set>
		    </feature>
		    <feature data="order">
			<order>
			    <constant data="df"/>
			    <constant data="^"/>
			</order>
		    </feature>
		</record>
	    </classDimension>
	    <classDimension idref="idlp">
		<record>
		    <feature data="blocks">
			<set>
			    <constant data="det"/>
			</set>
		    </feature>
		    <feature data="linkEnd">
			<set>
			    <list>
				<constant data="df"/>
				<constant data="det"/>
			    </list>
			</set>
		    </feature>
		</record>
	    </classDimension>
	    <classDimension idref="lex">
		<record>
		    <feature data="word">
			<variable data="Word"/>
		    </feature>
		</record>
	    </classDimension>
	</classConj>
    </classDef>
    <classDef id="pname">
	<variable data="Word"/>
	<variable data="Agrs"/>
	<classConj>
	    <classDimension idref="id">
		<record>
		    <feature data="in">
			<set>
			    <constantCard data="subj" card="opt"/>
			    <constantCard data="obj" card="opt"/>
			</set>
		    </feature>
		    <feature data="agrs">
			<variable data="Agrs"/>
		    </feature>
		</record>
	    </classDimension>
	    <classDimension idref="lp">
		<record>
		    <feature data="in">
			<set>
			    <constantCard data="mf" card="opt"/>
			</set>
		    </feature>
		</record>
	    </classDimension>
	    <classDimension idref="lex">
		<record>
		    <feature data="word">
			<variable data="Word"/>
		    </feature>
		</record>
	    </classDimension>
	</classConj>
    </classDef>
    <classDef id="fin">
	<variable data="Word"/>
	<variable data="Agrs"/>
	<classConj>
	    <classDimension idref="id">
		<record>
