=== xdgrulez/xdk/Extras/statistics.dtd
<!ELEMENT statistics (grammar,examples,mode,date,solutions,failures,timeout,reco,dimensions,principles,string*,counts,profilecounts?)>

<!ELEMENT grammar EMPTY>
<!ATTLIST grammar
          data CDATA #REQUIRED>

<!ELEMENT examples EMPTY>
<!ATTLIST examples
          data CDATA #REQUIRED
          count CDATA #REQUIRED>

<!ELEMENT mode EMPTY>
<!ATTLIST mode
          data CDATA #REQUIRED>

<!ELEMENT date EMPTY>
<!ATTLIST date
          data CDATA #REQUIRED>

<!ELEMENT solutions EMPTY>
<!ATTLIST solutions
          data CDATA #REQUIRED>

<!ELEMENT failures EMPTY>
<!ATTLIST failures
          data CDATA #REQUIRED>

<!ELEMENT timeout EMPTY>
<!ATTLIST timeout
          data CDATA #REQUIRED>

<!ELEMENT reco EMPTY>
<!ATTLIST reco
          data CDATA #REQUIRED>

<!ELEMENT dimensions (dimension*)>
<!ELEMENT dimension EMPTY>
<!ATTLIST dimension
          data CDATA #REQUIRED>

<!ELEMENT principles (principle*)>
<!ELEMENT principle EMPTY>
<!ATTLIST principle
          data CDATA #REQUIRED>

<!ELEMENT string (words,outputs,choices,depth,failed,succeeded,time,sprofile?)>
<!ATTLIST string
          id ID #REQUIRED>

<!ELEMENT words (#PCDATA)>

<!ELEMENT outputs (graph*)>

<!ELEMENT choices EMPTY>
<!ATTLIST choices
          data CDATA #REQUIRED>

<!ELEMENT depth EMPTY>
<!ATTLIST depth
          data CDATA #REQUIRED>

<!ELEMENT failed EMPTY>
<!ATTLIST failed
          data CDATA #REQUIRED>

<!ELEMENT succeeded EMPTY>
<!ATTLIST succeeded
          data CDATA #REQUIRED>

<!ELEMENT time EMPTY>
<!ATTLIST time
          data CDATA #REQUIRED>

<!ELEMENT sprofile (spnode*)>
<!ATTLIST sprofile
          varfdbool CDATA #REQUIRED
          varfdint CDATA #REQUIRED
          varfdtotal CDATA #REQUIRED
          varfs CDATA #REQUIRED
          vartotal CDATA #REQUIRED
          propcost CDATA #REQUIRED
          propcount CDATA #REQUIRED
          words CDATA #REQUIRED
	  entries CDATA #REQUIRED>
<!ELEMENT spnode EMPTY>
<!ATTLIST spnode
          index CDATA #REQUIRED
          word CDATA #REQUIRED
          entries CDATA #REQUIRED>

<!ELEMENT counts (cchoices,cdepth,cfailed,csucceeded,ctime)>

<!ELEMENT cchoices EMPTY>
<!ATTLIST cchoices
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT cdepth EMPTY>
<!ATTLIST cdepth
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT cfailed EMPTY>
<!ATTLIST cfailed
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT csucceeded EMPTY>
<!ATTLIST csucceeded
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT ctime EMPTY>
<!ATTLIST ctime
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT profilecounts (cvarfdbool,cvarfdint,cvarfdtotal,cvarfs,cvartotal,cpropcost,cpropcount,cwords,centries)>

<!ELEMENT cvarfdbool EMPTY>
<!ATTLIST cvarfdbool
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT cvarfdint EMPTY>
<!ATTLIST cvarfdint
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT cvarfdtotal EMPTY>
<!ATTLIST cvarfdtotal
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT cvarfs EMPTY>
<!ATTLIST cvarfs
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT cvartotal EMPTY>
<!ATTLIST cvartotal
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT cpropcost EMPTY>
<!ATTLIST cpropcost
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT cpropcount EMPTY>
<!ATTLIST cpropcount
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT cwords EMPTY>
<!ATTLIST cwords
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!ELEMENT centries EMPTY>
<!ATTLIST centries
          min CDATA #REQUIRED
          max CDATA #REQUIRED
          average CDATA #REQUIRED>

<!-- XML output DTD -->
<!ELEMENT graph (node*,edge*)>
<!ATTLIST graph
          dimension CDATA #REQUIRED>
<!ELEMENT node (attrs?,entry?,model?)>
<!ATTLIST node
          index CDATA #REQUIRED
	  word CDATA #REQUIRED
          label CDATA #IMPLIED>
<!ELEMENT edge EMPTY>
<!ATTLIST edge
          index1 CDATA #REQUIRED
          index2 CDATA #REQUIRED
          label CDATA #IMPLIED>
<!ELEMENT attrs (#PCDATA)>
<!ELEMENT entry (#PCDATA)>
<!ELEMENT model (#PCDATA)>

=== xdgrulez/xdk/XTAG/XDK_evaluation/filter_tagger/wsj23_35-39_XDK_nosubstitution.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE statistics SYSTEM "Extras/statistics.dtd">
<statistics>
  <grammar data="4712.ulsocket"/>
  <examples data="XTAG/XDK_evaluation/wsj23_35-39.txt" count="185"/>
  <date data="Jun 8, 2007 11:28:46"/>
  <solutions data="1"/>
  <failures data="9999"/>
  <timeout data="1800"/>
  <reco data="5"/>
  <dimensions>
    <dimension data="id"/>
    <dimension data="idlp"/>
    <dimension data="lex"/>
    <dimension data="lp"/>
  </dimensions>
  <principles>
    <principle data="id principle.graph1Constraints (id)"/>
    <principle data="id principle.graph1Dist (id)"/>
    <principle data="id principle.tree (id)"/>
    <principle data="id principle.in (id)"/>
    <principle data="id principle.out (id)"/>
    <principle data="id principle.xTAGRoot (id)"/>
    <principle data="lp principle.graph1Constraints (lp)"/>
    <principle data="lp principle.graph1Dist (lp)"/>
    <principle data="lp principle.tree (lp)"/>
    <principle data="lp principle.in (lp)"/>
    <principle data="lp principle.out (lp)"/>
    <principle data="lp principle.government (lp)"/>
    <principle data="lp principle.xTAG (lp)"/>
    <principle data="lp principle.parse (lp)"/>
    <principle data="idlp principle.xTAGLinking (id,lp,idlp)"/>
    <principle data="idlp principle.xTAGRedundant (id,lp)"/>
    <principle data="lex principle.entries ()"/>
  </principles>
  <gprofile fd="6" fs="204" fdfs="210" entries="204">
    <gpnode fd="2" fs="1" fdfs="3"/>
    <gpattrs fd="0" fs="0" fdfs="0">
      <gpdimension data="id" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="idlp" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="lex" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="lp" fd="0" fs="0" fdfs="0"/>
    </gpattrs>
    <gpentry fd="2" fs="106" fdfs="108">
      <gpdimension data="id" fd="0" fs="29" fdfs="29"/>
      <gpdimension data="idlp" fd="0" fs="25" fdfs="25"/>
      <gpdimension data="lex" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="lp" fd="2" fs="52" fdfs="54"/>
    </gpentry>
    <gpmodel fd="2" fs="97" fdfs="99">
      <gpdimension data="id" fd="1" fs="36" fdfs="37"/>
      <gpdimension data="idlp" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="lex" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="lp" fd="1" fs="61" fdfs="62"/>
    </gpmodel>
    <gplabel>
      <gpdimension data="id" label="28"/>
      <gpdimension data="idlp" label="0"/>
      <gpdimension data="lex" label="0"/>
      <gpdimension data="lp" label="25"/>
    </gplabel>
  </gprofile>
  <string id="string4">
    <words>
    this confusion effectively halted one form of program trading , stock index arbitrage , that closely links the futures and stock markets , and has been blamed by some for the market 's big swings .
    </words>
    <outputs>
    </outputs>
    <choices data="3758"/>
    <depth data="96"/>
    <failed data="3743"/>
    <succeeded data="0"/>
    <time data="1800170"/>
    <sprofile fd="335448" fs="99888" fdfs="435336" pr="573644" entries="8.8056" words="36">
      <spnode index="1" word="this" entries="2" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="2" word="confusion" entries="10" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="3" word="effectively" entries="4" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="4" word="halted" entries="27" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="5" word="one" entries="2" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="6" word="form" entries="3" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="7" word="of" entries="13" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="8" word="program" entries="10" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="9" word="trading" entries="3" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="10" word="," entries="8" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="11" word="stock" entries="10" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="12" word="index" entries="10" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="13" word="arbitrage" entries="10" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="14" word="," entries="8" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="15" word="that" entries="1" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="16" word="closely" entries="2" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="17" word="links" entries="23" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="18" word="the" entries="2" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="19" word="futures" entries="10" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="20" word="and" entries="11" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="21" word="stock" entries="10" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="22" word="markets" entries="10" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="23" word="," entries="8" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="24" word="and" entries="11" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="25" word="has" entries="29" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="26" word="been" entries="4" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="27" word="blamed" entries="18" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="28" word="by" entries="13" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="29" word="some" entries="2" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="30" word="for" entries="14" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="31" word="the" entries="2" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="32" word="market" entries="10" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="33" word="'s" entries="3" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="34" word="big" entries="9" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="35" word="swings" entries="3" fd="6" fs="213" fdfs="219" pr="335"/>
      <spnode index="36" word="." entries="2" fd="6" fs="213" fdfs="219" pr="335"/>
    </sprofile>
  </string>
      <spnode index="27" word="contact" entries="13" fd="6" fs="282" fdfs="288" pr="445"/>
      <spnode index="28" word="with" entries="18" fd="6" fs="282" fdfs="288" pr="445"/>
      <spnode index="29" word="both" entries="2" fd="6" fs="282" fdfs="288" pr="445"/>
      <spnode index="30" word="sides" entries="13" fd="6" fs="282" fdfs="288" pr="445"/>
      <spnode index="31" word="since" entries="5" fd="6" fs="282" fdfs="288" pr="445"/>
      <spnode index="32" word="the" entries="2" fd="6" fs="282" fdfs="288" pr="445"/>
      <spnode index="33" word="strike" entries="13" fd="6" fs="282" fdfs="288" pr="445"/>
      <spnode index="34" word="began" entries="43" fd="6" fs="282" fdfs="288" pr="445"/>
      <spnode index="35" word="." entries="2" fd="6" fs="282" fdfs="288" pr="445"/>
    </sprofile>
  </string>
  <string id="string15">
    <words>
    but Iraqi Iraqi said he thinks the earliest a pact could be struck would be the end of this month , hinting that the company and union may resume negotiations as early as this week .
    </words>
    <outputs>

=== xdgrulez/xdk/XTAG/XDK_evaluation/filter_simple/wsj23_25-29_XDK_nosubstitution.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE statistics SYSTEM "Extras/statistics.dtd">
<statistics>
  <grammar data="4712.ulsocket"/>
  <examples data="XTAG/XDK_evaluation/wsj23_25-29.txt" count="376"/>
  <date data="Jun 4, 2007 16:36:17"/>
  <solutions data="1"/>
  <failures data="9999"/>
  <timeout data="1800"/>
  <reco data="5"/>
  <dimensions>
    <dimension data="id"/>
    <dimension data="idlp"/>
    <dimension data="lex"/>
    <dimension data="lp"/>
  </dimensions>
  <principles>
    <principle data="id principle.graph1Constraints (id)"/>
    <principle data="id principle.graph1Dist (id)"/>
    <principle data="id principle.tree (id)"/>
    <principle data="id principle.in (id)"/>
    <principle data="id principle.out (id)"/>
    <principle data="id principle.xTAGRoot (id)"/>
    <principle data="lp principle.graph1Constraints (lp)"/>
    <principle data="lp principle.graph1Dist (lp)"/>
    <principle data="lp principle.tree (lp)"/>
    <principle data="lp principle.in (lp)"/>
    <principle data="lp principle.out (lp)"/>
    <principle data="lp principle.government (lp)"/>
    <principle data="lp principle.xTAG (lp)"/>
    <principle data="lp principle.parse (lp)"/>
    <principle data="idlp principle.xTAGLinking (id,lp,idlp)"/>
    <principle data="idlp principle.xTAGRedundant (id,lp)"/>
    <principle data="lex principle.entries ()"/>
  </principles>
  <gprofile fd="6" fs="280" fdfs="286" entries="408">
    <gpnode fd="2" fs="1" fdfs="3"/>
    <gpattrs fd="0" fs="0" fdfs="0">
      <gpdimension data="id" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="idlp" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="lex" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="lp" fd="0" fs="0" fdfs="0"/>
    </gpattrs>
    <gpentry fd="2" fs="150" fdfs="152">
      <gpdimension data="id" fd="0" fs="37" fdfs="37"/>
      <gpdimension data="idlp" fd="0" fs="37" fdfs="37"/>
      <gpdimension data="lex" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="lp" fd="2" fs="76" fdfs="78"/>
    </gpentry>
    <gpmodel fd="2" fs="129" fdfs="131">
      <gpdimension data="id" fd="1" fs="44" fdfs="45"/>
      <gpdimension data="idlp" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="lex" fd="0" fs="0" fdfs="0"/>
      <gpdimension data="lp" fd="1" fs="85" fdfs="86"/>
    </gpmodel>
    <gplabel>
      <gpdimension data="id" label="36"/>
      <gpdimension data="idlp" label="0"/>
      <gpdimension data="lex" label="0"/>
      <gpdimension data="lp" label="37"/>
    </gplabel>
  </gprofile>
  <string id="string2">
    <words>
    big investment banks refused to step up to the plate to support the beleaguered floor traders by buying big blocks of stock , traders say .
    </words>
    <outputs>
    </outputs>
    <choices data="3188"/>
    <depth data="86"/>
    <failed data="3171"/>
    <succeeded data="0"/>
    <time data="1800300"/>
    <sprofile fd="270192" fs="85860" fdfs="356052" pr="475570" entries="19.192" words="26">
      <spnode index="1" word="big" entries="3" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="2" word="investment" entries="3" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="3" word="banks" entries="23" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="4" word="refused" entries="49" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="5" word="to" entries="22" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="6" word="step" entries="35" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="7" word="up" entries="56" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="8" word="to" entries="22" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="9" word="the" entries="2" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="10" word="plate" entries="19" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="11" word="to" entries="22" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="12" word="support" entries="18" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="13" word="the" entries="2" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="14" word="beleaguered" entries="15" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="15" word="floor" entries="18" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="16" word="traders" entries="3" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="17" word="by" entries="18" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="18" word="buying" entries="54" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="19" word="big" entries="3" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="20" word="blocks" entries="19" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="21" word="of" entries="12" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="22" word="stock" entries="21" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="23" word="," entries="22" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="24" word="traders" entries="3" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="25" word="say" entries="33" fd="6" fs="319" fdfs="325" pr="503"/>
      <spnode index="26" word="." entries="2" fd="6" fs="319" fdfs="325" pr="503"/>
    </sprofile>
  </string>
  <string id="string3">
    <words>
    many money managers and some traders had already left their offices early Friday afternoon on a warm autumn day -- because the stock market was so quiet .
    </words>
    <outputs>
    </outputs>
    <choices data="3916"/>
    <depth data="62"/>
    <failed data="3903"/>
    <succeeded data="0"/>
    <time data="1800090"/>
    <sprofile fd="247268" fs="76989" fdfs="324257" pr="430972" entries="11.786" words="28">
      <spnode index="1" word="many" entries="7" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="2" word="money" entries="3" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="3" word="managers" entries="3" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="4" word="and" entries="11" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="5" word="some" entries="6" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="6" word="traders" entries="3" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="7" word="had" entries="43" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="8" word="already" entries="6" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="9" word="left" entries="43" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="10" word="their" entries="3" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="11" word="offices" entries="3" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="12" word="early" entries="8" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="13" word="Friday" entries="7" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="14" word="afternoon" entries="7" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="15" word="on" entries="19" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="16" word="a" entries="5" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="17" word="warm" entries="29" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="18" word="autumn" entries="7" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="19" word="day" entries="8" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="20" word="--" entries="10" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="21" word="because" entries="4" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="22" word="the" entries="2" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="23" word="stock" entries="21" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="24" word="market" entries="23" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="25" word="was" entries="4" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="26" word="so" entries="14" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="27" word="quiet" entries="29" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="28" word="." entries="2" fd="6" fs="260" fdfs="266" pr="409"/>
    </sprofile>
  </string>
      <spnode index="20" word="--" entries="10" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="21" word="because" entries="4" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="22" word="the" entries="2" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="23" word="stock" entries="21" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="24" word="market" entries="23" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="25" word="was" entries="4" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="26" word="so" entries="14" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="27" word="quiet" entries="29" fd="6" fs="260" fdfs="266" pr="409"/>
      <spnode index="28" word="." entries="2" fd="6" fs="260" fdfs="266" pr="409"/>
    </sprofile>
  </string>
  <string id="string4">
    <words>
    Iraqi Street 's political speculators , or risk dolphins , had placed unusually large bets that a takeover would succeed and Iraqi stock would rise .
    </words>
    <outputs>
